CREATE DATABASE IF NOT EXISTS notes;

USE notes;

CREATE TABLE IF NOT EXISTS users(
	id VARCHAR(20) PRIMARY KEY,
	firstName TEXT NOT NULL,
	lastName TEXT NOT NULL,
	email TEXT NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS notes(
	id VARCHAR(20) PRIMARY KEY,
	title TEXT NOT NULL,
	text TEXT NOT NULL,
	dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	user_id VARCHAR(20) NOT NULL REFERENCES users(id)
);